src/java/br/ufg/inf/si/model/GnomeDTO.java
/*
 * Data Transfer Object for gnome
 */
package br.ufg.inf.si.model;

/**
 *
 * @author maaahad
 */
public interface GnomeDTO {
    public String getId();
    public String getGnomeType();
    public float getGnomePrice();
    public int getGnomeTotal();
    public int getGnomeAvailable();
}

src/java/br/ufg/inf/si/model/OrderDTO.java
/*
 * Data Transfer Object for order
 */
package br.ufg.inf.si.model;

/**
 *
 * @author maaahad
 */
public interface OrderDTO {
    public String getOrderID();
    public int getAmountToBuy();
    public UserEntity getUser();
    
}

src/java/br/ufg/inf/si/model/UserDTO.java
/*
 * Data Transfer Object for user
 */
package br.ufg.inf.si.model;

/**
 *
 * @author maaahad
 * User DataTransfer Interface
 */
public interface UserDTO {
    public String getUserName();
    public String getPassword();
    public String getPermitStatus();
    public String getOnlineStatus();
    public String getUserRole();
}

web/add_item_page.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:form id="additemForm">
        <!-- Growl component -->
        <p:growl id="messages" showDetail="false"/>
        <p:dialog header="Add Item" widgetVar="additemDialog" height="300px" resizable="false">
            <h:panelGrid columns="2" cellpadding="5">
                
                <p:outputLabel for="itemName" value="Item: " />
                <p:inputText id="itemName" value="#{adminBean.productType}"/>
                <p:outputLabel for="itemPrice" value="Price: " />
                <p:inputText id="itemPrice" value="#{adminBean.productPrice}"/>
                <p:outputLabel for="itemTotal" value="Total: " />
                <p:inputText id="itemTotal" value="#{adminBean.productTotal}"/>
                <p:outputLabel for="itemAvailable" value="Available: " />
                <p:inputText id="itemAvailable" value="#{adminBean.productAvailable}"/>
                
                <p:commandButton id="confirm"  value="#{bundle.OK}" action="#{adminBean.addNewItem()}"  oncomplete="PF('additemDialog').hide()" update=":productForm:availableGnomes,:additemForm:messages" icon="ui-icon-check"/>
                <p:commandButton id="cancel"  value="#{bundle.Cancel}" onclick="PF('additemDialog').hide()" icon="ui-icon-cancel"/>
            </h:panelGrid>
        </p:dialog>
    </h:form>
</html>

web/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Error</title>
    </h:head>
    <h:body>
        <!-- Here we manage the error handling -->
        <ui:composition template="homePage.xhtml">
            <ui:define name="home_body_right_ui">
                <h1>Error</h1>
                <c:choose>
                    <c:when test="#{userBean.exception.cause != null}">
                        <h3>
                            <h:outputText value="#{userBean.exception.cause.message}"/>
                        </h3>
                    </c:when>
                    <c:otherwise>
                        <h3>
                            <h:outputText value="#{userBean.exception.message}"/>
                        </h3>
                    </c:otherwise>
                </c:choose>
                <a href="registration.xhtml">Voltar para a página de registro</a>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/gnome_list_page.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:form id="productForm">
        <!-- Growl component -->
        <p:growl id="messages" showDetail="false"/>

        <p:panel id="gnome-Panel" visible="false" header="Products" toggleable="true" closable="true" toggleSpeed="500" closeSpeed="300" widgetVar="gnomePanel" style="margin-top: 10px">

            <p:dataTable id="availableGnomes" var="gnomes" selectionMode="single" value="#{inventoryBean.gnomes}" rowKey="#{gnomes.id}" 
                         paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}" 
                         paginator="true" rows="5" style="margin-bottom: 10px">
                <f:facet name="header">
                    Produtos Disponíveis
                </f:facet>
                <!-- Adding ajax  selection listener.  -->
                <p:ajax event="rowSelect" listener="#{userBean.onRowSelect}" update=":productForm:messages"/>
                <p:ajax event="rowUnselect" listener="#{userBean.onRowUnselect}"/>

                <p:column style="text-align: left" headerText="#{bundle.ProductsID}">
                    <h:outputText value="#{gnomes.id}"/>
                </p:column>

                <p:column style="text-align: left" headerText="#{bundle.ProductsType}">
                    <h:outputText value="#{gnomes.gnomeType}"/>
                </p:column>

                <p:column  style="text-align: left" headerText="#{bundle.productsPrice}">
                    <h:outputText value="#{gnomes.gnomePrice}"/>
                </p:column>

                <p:column style="text-align: left" headerText="#{bundle.ProductsAvailable}">
                    <h:outputText value="#{gnomes.gnomeAvailable} of #{gnomes.gnomeTotal}"/>
                </p:column>

                <!-- Show edit item for admin to update amount of the current item -->
                <c:choose>
                    <c:when test="#{userBean.isOnline}">
                        <p:column style="text-align: center" rendered="#{userBean.currentUser.userRole eq bundle.Admin}">
                            <p:commandButton id="edit"  value="#{bundle.Edit}" onclick="PF('updateitemDialog').show()" icon="ui-icon-pencil"/>
                        </p:column>

                        <p:column style="text-align: center" rendered="#{userBean.currentUser.userRole eq bundle.Admin}">
                            <p:commandButton id="delete"  value="#{bundle.Delete}" onclick="PF('deleteitemDialog').show()" icon="ui-icon-trash"/>
                        </p:column>
                    </c:when>
                </c:choose>
                <!--
                <p:column style="text-align: center">
                    <p:commandButton id="select"  style="background-color: red" process="availableGnomes" update=":form:gnomeDetail"  value="#{bundle.SelectProduct}" oncomplete="PF('gnomeDialog').show()"/>
                </p:column>
                -->


                <f:facet name="footer">
                    <p:commandButton id="select" process="availableGnomes" update=":productForm:gnomeDetail"  value="#{bundle.SelectProduct}" onclick="PF('gnomeDialog').show()"/>
                </f:facet>

            </p:dataTable>

            <!-- This is the dialog after a row is selected for showing selected gnome's info and define amount -->
            <!-- modal="true" not working -->
            <p:dialog header="Gnome Info" widgetVar="gnomeDialog"  height="200px" resizable="false">
                <p:outputPanel id="gnomeDetail" style="text-align:center">
                    <!-- This panel is when a user selected a product(gnome) -->
                    <p:panelGrid  columns="1" rendered="#{not empty userBean.selectedGnome}" columnClasses="label,value">
                        <f:facet name="header">
                            This could be replaced by a Gnome picture 
                        </f:facet>
                        <h:outputLabel value="Amount to Buy "/>
                        <p:inputText id="amount" value="#{userBean.amountToCart}" />
                        <p:slider for="amount" />
                        <!-- After hitting the command button I want to hide the dialog box using "PF('widgetVat to be hide').hide()" -->
                        <!-- Need to update basket list as soon as user added to the basket -->
                        <p:commandButton id="add" value="#{bundle.AddToCart}" action="#{userBean.addToCart()}" oncomplete="PF('gnomeDialog').hide()" update=":productForm:availableGnomes,:productForm:messages,:basketForm:basketList"/>
                    </p:panelGrid>
                    <!-- This panel is for if the user don't select a product (gnome)-->
                    <p:panelGrid  columns="1" rendered="#{empty userBean.selectedGnome}" columnClasses="label,value">
                        <h:outputLabel value="Select a product from the list"/>
                        <p:commandButton value="#{bundle.OK}" onclick="PF('gnomeDialog').hide()" icon="ui-icon-check"/>
                    </p:panelGrid>
                </p:outputPanel>
            </p:dialog>

            <!-- This dialog pop up when a admin want to add or remove amount of a item -->


            <p:dialog id="updateItemAmount" header="Update Existing Item Amount" widgetVar="updateitemDialog" height="100px" resizable="false">
                <p:panelGrid columns="2" columnClasses="label,value">
                    <h:outputLabel value="#{bundle.Amount}" />
                    <h:inputText value="#{adminBean.amountToAdd}"/>
                    <p:commandButton id="confirmEdit" value="#{bundle.OK}" action="#{adminBean.updateExistingProduct()}" oncomplete="PF('updateitemDialog').hide()" update=":productForm:availableGnomes,:productForm:messages" icon="ui-icon-check"/>
                    <p:commandButton id="cancelEdit" value="#{bundle.Cancel}" onclick="PF('updateitemDialog').hide()" icon="ui-icon-cancel"/> 
                </p:panelGrid>
            </p:dialog>

            <!-- This will pop up when the admin want to delete an existing item-->
            <p:dialog id="deleteItem" header="Delete Existing Item Amount" widgetVar="deleteitemDialog" height="100px" resizable="false">
                <p:panelGrid columns="2" columnClasses="label,value">
                    <p:commandButton id="confirmDelete" value="#{bundle.OK}" action="#{adminBean.deleteExistingProduct()}" oncomplete="PF('deleteitemDialog').hide()" update=":productForm:availableGnomes,:productForm:messages,:basketForm:basketList" icon="ui-icon-check"/>
                    <p:commandButton id="cancelDelete" value="#{bundle.Cancel}" onclick="PF('deleteitemDialog').hide()" icon="ui-icon-cancel"/> 
                </p:panelGrid>
            </p:dialog>

            <!-- Keep the cart Page to pass the reference to the delete option for update -->
            <ui:include src="user_basket_page.xhtml"/>
        </p:panel>
    </h:form>

</html>

web/log_reg_page.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:form id="logregForm">
        <!-- Error Handling -->
        <p:growl id="logreg-message"/>
        <!-- This following dialog will be pop up when we click on log in -->
        <p:dialog header="Login" widgetVar="loginDialog" height="200px" resizable="false">
            <p:panelGrid id="loginPanel" columns="2">
                <f:facet name="header">
                    Login Form
                </f:facet>
                <h:outputLabel value="#{bundle.UserName}" />
                <p:inputText  value="#{userBean.userName}"/>
                <h:outputLabel value="#{bundle.Password}" />
                <p:password value="#{userBean.password}"/>
                <!-- Login User -->
                <f:facet name="footer">
                    <p:commandButton id="loginButton"  value="#{bundle.Submit}" action="#{userBean.logInUser()}" update=":logregForm:logreg-message"/>
                </f:facet>
            </p:panelGrid>
        </p:dialog>

        <!-- The following dialog will pop up when the user clicked registration button -->
        <p:dialog header="Registration" widgetVar="registrationDialog" height="200px" resizable="false">
            <p:panelGrid id="registrationPanel" columns="2">
                <f:facet name="header">
                    Formulário de Registro
                </f:facet>

                <h:outputLabel value="#{bundle.UserName}" />
                <p:inputText  value="#{userBean.userName}"/>
                <h:outputLabel value="#{bundle.Password}" />
                <p:password value="#{userBean.password}"/>

                <!-- Register new User -->
                <f:facet name="footer">
                    <p:commandButton id="registerButton"  value="#{bundle.Submit}" action="#{userBean.registerUser()}" update=":logregForm:logreg-message"/>
                </f:facet>
            </p:panelGrid>
        </p:dialog>
    </h:form>
</html>

web/login_page.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:form id="logForm">
        <!-- Error Handling -->
        <p:growl id="log-message"/>
        <!-- This following dialog will be pop up when we click on log in -->
        <p:dialog header="Login" widgetVar="loginDialog" height="200px" resizable="false">
            <p:panelGrid id="loginPanel" columns="2">
                <f:facet name="header">
                    Formulário de Login
                </f:facet>
                <h:outputLabel value="#{bundle.UserName}" />
                <p:inputText  value="#{userBean.userName}"/>
                <h:outputLabel value="#{bundle.Password}" />
                <p:password value="#{userBean.password}"/>
                <!-- Login User -->
                <f:facet name="footer">
                    <p:commandButton id="loginButton"  value="#{bundle.Submit}" action="#{userBean.logInUser()}" update=":navigation-form,:productForm:availableGnomes,:logForm:log-message" oncomplete="PF('loginDialog').hide()"/>
                </f:facet>
            </p:panelGrid>
        </p:dialog>
    </h:form>
</html>

web/registration_page.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:form id="regForm">
        <!-- Error Handling -->
        <p:growl id="reg-message"/>
        <!-- The following dialog will pop up when the user clicked registration button -->
        <p:dialog header="Registration" widgetVar="registrationDialog" height="200px" resizable="false">
            <p:panelGrid id="registrationPanel" columns="2">
                <f:facet name="header">
                    Formulário de Registro
                </f:facet>

                <h:outputLabel value="#{bundle.UserName}" />
                <p:inputText  value="#{userBean.userName}"/>
                <h:outputLabel value="#{bundle.Password}" />
                <p:password value="#{userBean.password}"/>

                <!-- Register new User -->
                <f:facet name="footer">
                    <p:commandButton id="registerButton"  value="#{bundle.Submit}" action="#{userBean.registerUser()}" update=":navigation-form,:regForm:reg-message"/>
                </f:facet>
            </p:panelGrid>
        </p:dialog>
    </h:form>
</html>

web/user_basket_page.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


    <h:form id="basketForm">
        <p:growl id="cartMessage"/>
        <p:dialog header="My Cart" widgetVar="mycartDialog" height="200px" width="800px" resizable="false">
            <p:dataTable id="basketList" var="order" selectionMode="single" value="#{userBean.ordersList}" rowKey="#{order.orderID}">
                <f:facet name="header">
                    Detalhes do Pedido
                </f:facet>
                <!-- Need to add ajax listener for row selection and un-selection -->
                <p:ajax event="rowSelect" listener="#{userBean.onCartRowSelect}" update=":basketForm:cartMessage"/>
                <p:ajax event="rowUnselect" listener="#{userBean.onCartRowUnselect}" update=":basketForm:cartMessage"/>

                <p:column style="text-align: left" headerText="Order ID">
                    <h:outputText value="#{order.orderID}"/>
                </p:column>
                <p:column style="text-align: left" headerText="Product Name">
                    <h:outputText value="#{order.gnome.gnomeType}"/>
                </p:column>
                <p:column style="text-align: left" headerText="Price per Product">
                    <h:outputText value="#{order.gnome.gnomePrice}"/>
                </p:column>

                <p:column style="text-align: left" headerText="Amount">
                    <h:outputText value="#{order.amountToBuy}"/>
                </p:column>

                <p:column style="text-align: center">
                    <p:commandButton id="delete" value="#{bundle.Delete}" onclick="PF('deleteDialog').show()" update=":basketForm:cartMessage" icon="ui-icon-trash"/>
                </p:column>

                <p:column style="text-align: center">
                    <p:commandButton id="edit" value="#{bundle.Edit}" icon="ui-icon-pencil"/>
                </p:column>
                
                <f:facet name="footer">
                    <p:commandButton id="checkout" value="#{bundle.Checkout}" action="#{userBean.toCheckOut()}" oncomplete="PF('checkoutDialog').show()" update=":basketForm:checkout,:basketForm:cartMessage" icon="ui-icon-suitcase"/>
                </f:facet>

            </p:dataTable>
        </p:dialog>

        <p:dialog header="Delete Order" widgetVar="deleteDialog" height="50px" resizable="false">
            <p:commandButton id="confirmDelete" value="#{bundle.Confirm}" action="#{userBean.deleteFromCart()}" oncomplete="PF('deleteDialog').hide()" update=":productForm:availableGnomes,:basketForm:basketList,:basketForm:cartMessage"/>
        </p:dialog>

        <p:dialog id="checkout" header="Checkout" widgetVar="checkoutDialog" height="120px" resizable="false">
            <!-- If Cart is not empty -->
            <p:panelGrid columns="2" columnClasses="label,value" rendered="#{not empty userBean.ordersList}">
                <h:outputLabel value="#{bundle.Total}" />
                <h:outputText  value="#{userBean.totalToPay}"/>
                <p:commandButton id="confirmCheckout" value="#{bundle.Buy}" action="#{userBean.toPayAndBuy()}" oncomplete="PF('checkoutDialog').hide()" update=":basketForm:basketList,:basketForm:cartMessage" icon="ui-icon-check"/>
                <p:commandButton id="cancelCheckout" value="#{bundle.Cancel}" onclick="PF('checkoutDialog').hide()" icon="ui-icon-cancel"/>
            </p:panelGrid>
            <!-- If Cart is empty -->
            <p:panelGrid columns="2" columnClasses="label,value" rendered="#{empty userBean.ordersList}">
                <h:outputLabel value="#{bundle.CartEmpty}" />
                <p:commandButton id="cancelCheckout2" value="#{bundle.OK}" onclick="PF('checkoutDialog').hide(),PF('mycartDialog').hide()" icon="ui-icon-check"/>
            </p:panelGrid>

        </p:dialog>

        <!-- Need a reference of the product list(here gnomelist) as to update after deletion from the order-->
        
        <!-- To make it work properly the list should have been in a dialog, otherwise it will populate the center of the body-->
    </h:form>
</html>

web/user_list_page.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:form id="userlistForm">
        <!-- Growl component -->
        <p:growl id="messages" showDetail="false"/>
        <p:dialog header="Registered Users" widgetVar="userlistDialog" height="300px" resizable="false">

            <p:dataTable id="registeredUsers" var="user" selectionMode="single" value="#{adminBean.usersList}" rowKey="#{user.userName}">
                <f:facet name="header">
                    Select to edit user's properties ...
                </f:facet>
                <!-- Adding ajax  selection listener.  -->
                <p:ajax event="rowSelect" listener="#{adminBean.onRowSelect}" update=":userlistForm:messages"/>
                <p:ajax event="rowUnselect" listener="#{adminBean.onRowUnselect}"/>

                <p:column style="text-align: center" headerText="#{bundle.UserName}">
                    <h:outputText value="#{user.userName}"/>
                </p:column>

                <p:column style="text-align: center" headerText="#{bundle.Password}">
                    <h:outputText value="#{user.password}"/>
                </p:column>

                <p:column  style="text-align: center" headerText="#{bundle.OnlineStatus}">
                    <h:outputText value="#{user.onlineStatus}"/>
                </p:column>

                <p:column style="text-align: center" headerText="#{bundle.PermitStatus}">
                    <h:outputText value="#{user.permitStatus}"/>
                </p:column>

                <p:column style="text-align: center" headerText="#{bundle.Role}">
                    <h:outputText value="#{user.userRole}"/>
                </p:column>

                <!--
                <p:column style="text-align: center">
                    <p:commandButton id="select"  style="background-color: red" process="availableGnomes" update=":form:gnomeDetail"  value="#{bundle.SelectProduct}" oncomplete="PF('gnomeDialog').show()"/>
                </p:column>
                -->
                <p:column style="text-align: center">
                    <p:commandButton id="edit"  value="#{bundle.Edit}" onclick="PF('userinfoDialog').show()" icon="ui-icon-pencil"/>
                </p:column>

            </p:dataTable>

        </p:dialog>

        <!-- This is the dialog when a user is selected to edit-->
        <p:dialog header="Edit user's Info" widgetVar="userinfoDialog" height="200px" resizable="false">
            
            <p:panelGrid columns="2" columnClasses="label,value">
                
                <p:outputLabel for="onlineStatus" value="#{bundle.OnlineStatus}"/>
                <p:selectOneMenu id="onlineStatus" value="#{adminBean.userOnlineStatus}" style="width: 125px">
                    <f:selectItem itemLabel="#{bundle.SelectOne}" itemValue=" " />
                    <f:selectItem itemLabel="#{bundle.Online}" itemValue="#{bundle.Online}"/>
                    <f:selectItem itemLabel="#{bundle.Offline}" itemValue="#{bundle.Offline}"/>
                </p:selectOneMenu>
                
                <p:outputLabel for="permitStatus" value="#{bundle.PermitStatus}"/>
                <p:selectOneMenu id="permitStatus" value="#{adminBean.userPermitStatus}" style="width: 125px">
                    <f:selectItem itemLabel="#{bundle.SelectOne}" itemValue=" " />
                    <f:selectItem itemLabel="#{bundle.Permitted}" itemValue="#{bundle.Permitted}"/>
                    <f:selectItem itemLabel="#{bundle.Banned}" itemValue="#{bundle.Banned}"/>
                </p:selectOneMenu>

                <p:outputLabel for="userStatus" value="#{bundle.Role}"/>
                <p:selectOneMenu id="userStatus" value="#{adminBean.userRole}" style="width: 120px">
                    <f:selectItem itemLabel="#{bundle.SelectOne}" itemValue=" " />
                    <f:selectItem itemLabel="#{bundle.Admin}" itemValue="#{bundle.Admin}"/>
                    <f:selectItem itemLabel="#{bundle.Buyer}" itemValue="#{bundle.Buyer}"/>
                </p:selectOneMenu>
                
                <p:commandButton id="confirm"  value="#{bundle.OK}" action="#{adminBean.updateUserInfo()}" update=":userlistForm:messages,:userlistForm:registeredUsers" oncomplete="PF('userinfoDialog').hide()" icon="ui-icon-check"/>
                <p:commandButton id="cancel"  value="#{bundle.Cancel}" onclick="PF('userinfoDialog').hide()" icon="ui-icon-cancel"/>

            </p:panelGrid>
        </p:dialog>
    </h:form>
</html>

web/user_role_page.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <!-- This will be shown if the user is online -->
    <c:choose>
        <c:when test="#{userBean.isOnline}">
            <!-- Use admin or buyer seller menu based on the role of the user. Need to add actionListener to menuitem-->
            <!-- For simplicity use pop up dialog for all possible menu item-->
            <p:menuButton value="admin" rendered="#{userBean.currentUser.userRole eq bundle.Admin}">
                <p:menuitem value="View Users" onclick="PF('userlistDialog').show()" icon="ui-icon-disk"/>
                <p:menuitem value="Add Item" onclick="PF('additemDialog').show()" icon="ui-icon-circle-plus"/>
                <p:menuitem value="Update Item" onclick="PF('gnomePanel').show()" icon="ui-icon-pencil"/>
            </p:menuButton>
            <!-- Both buyer and admin have the buyer functionality-->
            <p:separator />
            <p:menuButton value="buyer">
                <p:menuitem value="My details" icon="ui-icon-disk" />
                <p:menuitem value="Current Order" icon="ui-icon-close" />
                <p:menuitem value="Orders History" icon="ui-icon-extlink" />
            </p:menuButton>

            <p:separator />
            <!-- User Info-->
            <p:button value="#{userBean.currentUser.userName}" icon="ui-icon-person"/>
            <p:separator />
            <h:outputText value=" Role: #{userBean.currentUser.userRole}"/>
        </c:when>
    </c:choose>

</html>